-- Create TOURIST table
CREATE TABLE IF NOT EXISTS TOURIST (
    TouristID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    PhoneNo INT NOT NULL,
    EmailID VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    Age INT NOT NULL,
    Password VARCHAR(64) NOT NULL
);


